// <auto-generated />
namespace MeCafeUber.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_Memo_Remarks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_Memo_Remarks));
        
        string IMigrationMetadata.Id
        {
            get { return "201809140708218_add_Memo_Remarks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
